### ISSUE TITLE
--use-swaplink を用いると，文字列データアトムを自由リンクに接続出来ない

### ISSUE THREAD

**Issue by sano-jin** [lmntal/lmntal-compiler#100]
```
res = a("b").
R = a(B) :- unary(B) | R = B.
```
を `--use-swaplink` をつけてコンパイル後，通常実行するとセグフォや使っていないはずのスペシャルアトム<set>をダンプするなどの現象が起きます．
`--slimcode` と `-O3` をつけても同様．

どうやら，

- `--use-swaplink` オプションをつけて
- 文字列を
- unary や string でマッチし
- 自由リンクにつなげる

とダメなようです．

中間命令列をみると `--use-swaplink` の場合のみ `relink` がないのでその影響ではと考えています．

int の場合は問題ないようです．

**Comment by k-ueda** [comment]
これはどうも issue #4 と同じ理由のようで，対症療法的な版を fix/issue4 としてプッシュしました．
（relink は Compactor.java が生成するCISC命令なので追いかけるのに一工夫必要です．）
issue #4 と #100 の例題は通るけど，通らない例題もあることがわかっているので，もう少し改良します．

**Comment by k-ueda** [comment]
右辺の単項の型付きプロセス文脈の引数（の相棒）がどこ（左辺，右辺のアトム，右辺の型付きプロセス文脈）に出てきても動くようにした（つもりの）版をプッシュしました．
なお現在の --use-swaplink は ground 型や（膜に伴う）プロセス文脈を含むルールは対象にしていないので，--use-swaplink なしのコードとしてこれまで通り動きます．
