### ISSUE TITLE
特定の順で等号が用いられたルールを渡すと NullPointerException が発生する

### ISSUE THREAD

**Issue by ayhsmt97** [lmntal/lmntal-compiler#113]
# 現象
以下のルールが記述されたプログラムをコンパイラに渡すと NullPointerException が発生する。
```
h = !A, !A = a :- h = !A, !A = a.
```
# 試したこと
- コンパイラを 2018 年のコミットまで戻したが、同様に例外が発生した
- hl オプション・最適化オプションの有無に関わらず例外が発生した
- 類似プログラムの入力
```
 % NullPointerException
 h = !A, !A = a :- h = !A, !A = a.

 % NullPointerException
 h = $a, $a = a :- n = $a, $a = a.

 % NullPointerException
 h = !A, !B = b, !A = a :- !A = h, !B = b, !A = a.

 % ok
 !A = h :- !A = h.
 
 % ok
 h = !A :- h = !A.
 
 % ok
 h = A, A = a :- h = A, A = a.
 
 % ok
 !A = h, !A = a :- !A = h, !A = a.
 
 % ok
 h = !A, a = !A :- h = !A, a = !A.

 % ok
 !A = h, a = !A :- !A = h, a = !A.
 
 % ok
 h = !A, !B = a :- h = !A, !B = a.
 
 % ok
 h = !A :- h = !A, !A = a.
```

**Comment by ayhsmt97** [comment]
### 調査
ルールのヘッド部に同名の型付きプロセス文脈 (ハイパーリンクに限らず) が特定の順で記述されていると NullPointerException が発生するようです。
たとえば、以下のルールも同じ例外が発生します。
`a = A, A = b :- int(A) | .`
順番を変えたら例外が発生せず、コンパイルが通ります。
`A = a, b = A :- int(A) | .`
また、型付きでなければ例外が発生せず、コンパイルが通ります。
`a = A, A = b :- |.`
連続した同名の型付きプロセス文脈2つがヘッド部に現れると例外が発生すると思われます。
実際、スタックトレースによると `compile.HeadCompiler.sameProcessContext` で例外が発生しているようです。

**Comment by ayhsmt97** [comment]
### 調査2
`compile.HeadCompiler.sameProcessContext` 内で NullPointerException が発生した箇所を特定しました。
`for (int j = 0; j < oriatom.args.length; j++) {`  の行で参照している `oriatom` が Null になっているのが原因です。
このあたりでは、膜の中のアトムのリンクを辿っていき、既存のリンクとの名前被りがあるような場合に中間命令 findproccxt を挿入します (おそらく)。
内部的には同名のリンクも別の名前で管理されますが、`sameNameMap` という HashMap でリンク名どうしの紐づけが行われます。
例外が発生するルールの実行では、あるアトムのもつリンクが `sameNameMap` によって別のリンクと同名とされているにも関わらず、その別のリンクはアトムとリンクの対応表 `linkNameToAtomMap` に含まれていない、という状況が発生します。
結果、`sameNameMap` から引いてきたリンク名をキーとして `linkNameToAtomMap` から取得するアトムが Null になってしまいます。
例外が発生せず正常終了するルールの実行では、アトムのリンク名が `sameNameMap` のキーと被らないため(なんで?)、そもそも `oriatom` を参照する機会がないようです。
何らかの理由でアトムのもつリンク名の割り当てが間違ってしまっている可能性を調査する必要がありそうです。

**Comment by k-ueda** [comment]
調査２のような怪しい状況が発生する原因を調べました．
例外が出るルールは頭部で = を使っていて，これはコンパイル時に RuleCompiler.java の staticUnify で除去します．
つまり a=$a（a=A の A はここではプロセス文脈）は最初は L1=L2, a(L1), $a[L2] だけど これを a(L1), $a[L1] か
a(L2), $a[L2] にします．このように，= の除去にあたってリンク名の付け替えを行いますが，プロセス文脈の   
内部リンク名（~3 のような形式で，プロセス文脈の内部名と同一視される）は事前に procCxtNameToLinkName
で変換されたものが sameNameMap などで使われるため，プロセス文脈のリンク名を付け替えないようにする
必要があります．
（代案として事前に決めたリンク名も一斉に付け替えることも考えられるが，こっちのほうがはるかに面倒．）
fix/113 に修正案をプッシュしました．
