### ISSUE TITLE
初期グラフにハイパーリンクが書けるようにする

### ISSUE THREAD

**Issue by nikosai** [lmntal/lmntal-compiler#18]
現在、ルールの左辺・右辺に登場する `!X` はハイパーリンクとして（正常に）解釈されている。
だが、初期グラフに登場する `!X` は **通常のリンクとして** 解釈されてしまっている。
例えば、 `a(!X,!X)` は `a(L,L)` と同じグラフという扱いになっている。
また、`a(!X)` は Global Singleton Link である旨の警告が出るし、 `a(!X,!X,!X)` は構文エラーとなる。

これらを正しくハイパーリンクとして解釈できるようにしたい。

**Comment by nikosai** [comment]
関連して、同一スコープ内に `!X` と `X` が共存している場合、現時点では同じモノとみなされてしまうらしい。
```
echo ':- uniq | a(!X),b(!X),c(!X),d(X)' | lmntal --stdin-lmn --hl-opt --slimcode | slim --hl -
```
は、
```
a(!H3). b(!H3). c(!H3). d(!H3). @4.
```
を返す。

**Comment by nikosai** [comment]
`src/compile/parser/SrcRule.java` の `addHyperLonkConstraint` あたりが強く関係しそう。

**Comment by k-ueda** [comment]
さきほど feature/toplevel-hl のPRを出してからこちらに目を通しました．
上記の問題のうち，2019-08-13 の
> 同一スコープ内に !X と X が共存している場合、現時点では同じモノとみなされてしまうらしい。
は未解決ですが，実害はないので，こちらは上記のmerge終了後に別途ブランチを切って修復します．
ここまで終わると，feature/init-hyperlink と（feature/ なしの）toplevel-hl，および issue #18,#22 は完了になると思います
（間違っていたら指摘してください）．
