### ISSUE TITLE
CUPとJFlexの更新

### ISSUE THREAD

**Issue by nikosai** [lmntal/lmntal-compiler#24]
CUPとJFlexで生成されるファイルでwarningが大量発生している。
[このページ](https://versioncontrolseidl.in.tum.de/parsergenerators/cup/blob/master/changelog.txt)によると、CUP version 0.11a beta 20050628でジェネリックが導入されるなどしているらしい。
また、[JFlexも更新されているらしい](https://jflex.de/)。

**Comment by 8q** [comment]
warningがどこで出ているのか確認できませんでしたが、新しいバージョンが出ているのであれば対応が必要そうです。

**Comment by nikosai** [comment]
確か、TypeScriptの“any型汚染”みたいに、CUPの出力に型がつかないから連鎖的にジェネリック型が解決できないとかそういう問題だった気がする

**Comment by nikosai** [comment]
closed by #68.
