### ISSUE TITLE
不要なcheckVersion()

### ISSUE THREAD

**Issue by ryotosaito** [lmntal/lmntal-compiler#27]
# 概要
## 問題点
- `src/runtime/FrontEnd.java` の `checkVersion()` はバージョン互換性がない
## 到達点
- [ ] `src/runtime/FrontEnd.java` の `checkVersion()` を削除、あるいは`System.getProperty("java.version")` を `"."` でtokenizeしない実装にする

# 詳細
`src/runtime/FrontEnd.java` の `checkVersion()` はJava 1.4未満を用いていないかをチェックしているが、現在1.4を用いる環境は非常に限定的である。

また、それどころか一部のJVMでは `System.getProperty("java.version")` で `"10"` など `"."` を含まない文字列を返し、Tokenizerの処理に悪影響を及ぼしている。

**Comment by 8q** [comment]
プログラム内でわざわざチェックしなくても、LMNtalコンパイラの要件にJava 1.4以上を用いることを含めれば `checkVersion()` は削除で良いと思います。

おっしゃるとおり `java.version` を分割して判定するのはバグの温床になるかと思います。
