### ISSUE TITLE
macOSでlmntalコンパイラが実行できない

### ISSUE THREAD

**Issue by 8q** [lmntal/lmntal-compiler#31]
macOSで実行できない状態になってしまっている。ビルドはできる。
以下コミットでrealpathコマンドが使われるようになったのに対して、macにはrealpathコマンドが存在しないため。

https://github.com/lmntal/lmntal-compiler/commit/ef761e441b9dc5343fd5bc69a849131afd82b657

**Comment by nikosai** [comment]
コミット ef761e4 の意図は、snapcraftでのビルドの際にコケたので直した、だったと思います。
詳細はあまり記憶にないのですが……。

**Comment by nikosai** [comment]
思い出しました。
snapcraftの仮想環境上では、`/usr/lib/lmntal-compiler` にGitHubからcloneしてきたリポジトリをまるごと置いて、`/usr/lib/lmntal-compiler/bin/lmntal` へのシンボリックリンクを `/usr/bin/lmntal` に置くという運用になっていて、その場合だとrealpathがないと誤作動するのでした。

シンボリックリンク周りに詳しくないので、そもそもこの運用が正しいのかがわからない……。

**Comment by shira-mg** [comment]
macであるかlinuxであるか、というより、coreutilsをインストールしているかどうかという問題のようです。

また、古いcoreutilsにはrealpathが含まれていないようなので、例えばroquefortはcoreutilsのバージョンが8.4なのでrealpathコマンドが存在しません。

coreutilsのバージョンをlmntalコンパイラの要件に含めるか、readlinkコマンドでも同等のことができるようなので、そちらに置き換えてしまうのも手かと思います。

**Comment by shira-mg** [comment]
以下のプルリクでTravisのテストにOSXによる実行も含めたのですが、TravisのOSXイメージにはcoreutilsが既に含まれてしまっているようなので、この件に関しては再現ができません。

https://github.com/lmntal/lmntal-compiler/pull/32

**Comment by 8q** [comment]
@nikosai
macであるかlinuxであるか、というより、coreutilsをインストールしているかどうかという問題のようです。

また、古いcoreutilsにはrealpathが含まれていないようなので、例えばroquefortはcoreutilsのバージョンが8.4なのでrealpathコマンドが存在しません。

coreutilsのバージョンをlmntalコンパイラの要件に含めるか、readlinkコマンドでも同等のことができるようなので、そちらに置き換えてしまうのも手かと思います。

こういった件が発見できるよう #32 でmacOSの自動テストも導入したのですが、TravisのOSXイメージにはcoreutilsが既に含まれてしまっているようなので再現できませんでした...。あまり意味がなかったかもしれません。

**Comment by 8q** [comment]
@nikosai 
そもそもですが、/usr/binにシンボリックリンクを貼るのが単にパスを通すことが目的であれば、シンボリックリンクを貼るのではなくlmntal-compiler/binを$PATHに追加するでも良いと思います。であればrealpathを使わずに済みそうです。

**Comment by nikosai** [comment]
@8q 
[これ](https://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f)によれば、`realpath` を単に `readlink -f` にreplaceすれば良さげな気がします。

**Comment by 8q** [comment]
@nikosai 記事でも言及されている通り、BSDでは正規化オプションがないので、`-f`は使えません

**Comment by 8q** [comment]
@nikosai 方針としてはこんな感じのことをイメージしています。
```
#!/bin/bash

if [ -L "$0" ]; then
  echo "symbol"
  myPath=$(readlink "$0")
else
  myPath="$0"
fi

echo "parent dir: $(cd $(dirname "$myPath") && pwd)"
```
