### ISSUE TITLE
slimcode生成に必要な部分だけを残す

### ISSUE THREAD

**Issue by 8q** [lmntal/lmntal-compiler#35]
LMNtalの処理系は事実上SLIMになっており、ほとんどの場合Java製処理系は使われないので、コンパイラからslimcode生成に必要な部分以外を削除する。Java製処理系を使う場合には `v1.45` 以前を使ってもらうことにする。`if(Env.slimcode)` 等の分岐のうち、slimcodeじゃない方の分岐を削除する。`--slimcode`オプションはあってもなくても良い状態にする。

**Comment by 8q** [comment]
そういえば `--compileonly` というオプションももう意味をなさない気がします。

**Comment by ryotosaito** [comment]
そうですね、同じ #39 で良ければ直します
`--compileonly` って今基本的に使われてないですよね…？
もう `Invalid option` を返しちゃってもいいかも

**Comment by 8q** [comment]
@ryotosaito 別でissue立てました。 #46
