### ISSUE TITLE
Rename HeadCompiler.enumFormals

### ISSUE THREAD

**Issue by y-tsune** [lmntal/lmntal-compiler#64]
HeadCompiler.enumFormalsは名前が謎なので変えた方が良いと思います
`void enumFormals(Membrane mem)`

> 膜memの子孫の全てのアトムと膜を、それぞれリストatomsとmemsに追加する。リスト内の追加された位置がそのアトムおよび膜の仮引数IDになる

**Comment by ryotosaito** [comment]
`RuleCompiler.compile()` で以下のように呼び出されています。
```java
hc = new HeadCompiler();
hc.enumFormals(rs.leftMem);
```
メソッドの中身から察するに空の`HeadCompiler`に`Membrane`内のコンパイルオブジェクトを詰め込んでいるようなので、`HeadCompiler.pushMembrane` みたいな名前が良さそうです

**Comment by 8q** [comment]
#62 で若干状況が変わっています。
