### ISSUE TITLE
$LMNTAL_HOMEを設定していても警告される

### ISSUE THREAD

**Issue by yoshrc** [lmntal/lmntal-compiler#9]
環境変数LMNTAL_HOMEを設定した状態で、LMNtal Compilerを実行しても、

```
Warning : LMNTAL_HOME is not set. Using relative path.
```

という警告が出ます。ちなみに、LMNTAL_HOMEの値は

```
/Users/yoshrc/eclipse_lmntal/LMNtal Compiler
```

です。

**Comment by 8q** [comment]
状況が再現できないので一旦ラベルをquestionにしました。

**Comment by 8q** [comment]
モジュールを使ったとき起きることがあるらしい(?)
もしかしたらもう直っているかも

警告はコードの[この部分](https://github.com/lmntal/lmntal-compiler/blob/f1fbd2a5250c005c76e6ba6fde5472bf16c9b0c1/src/compile/Module.java#L52)から出ている

**Comment by adachi-r** [comment]
少なくとも自分の環境では発生していない模様
あとLMNTAL_HOMEが正しく設定されていない場合は「lmntalというコマンドは存在しない」という表示が出力される

**Comment by adachi-r** [comment]
自分の環境ではLMNTAL_HOMEのパスが正しく設定されている場合は警告が出ず、正しく設定されていない場合「lmntalというコマンドは存在しない」というエラーが出力される

**Comment by 8q** [comment]
@adachi-r lmntalコマンドが見つからないになるのは
```
export LMNTAL_HOME="/path/to/lmntal-compiler"
export PATH="$LMNTAL_HOME/bin/$PATH"
```
としているからではないでしょうか？

LMNTAL_HOMEの有無で警告が出る出ないをテストするにはPATHがLMNTAL_HOMEに依存しないようにして
```
export LMNTAL_HOME="/path/to/lmntal-compiler"
export PATH="/path/to/lmntal-compiler/bin/$PATH"
```
として、`export LMNTAL_HOME="/path/to/lmntal-compiler"`の行を消したり戻したりして様子を見る必要がありそうな気がします。 `source ~/.bashrc` するのもお忘れなく

**Comment by adachi-r** [comment]
.bashrc内でPATHをLMNTAL_HOMEの依存から開放したところ、LMNTAL_HOMEをコメントアウトした際も警告が表示されないことを確認

**Comment by 8q** [comment]
再現できないので一旦クローズしましょう。
