### ISSUE TITLE
「\」の左のstring型アトムが反応後に普通のアトムになる

### ISSUE THREAD

**Issue by ghost** [lmntal/lmntal-compiler#94]
# 「\」の左のstring型アトムが反応後に普通のアトムになる
```
 str("a").
 match.
 str("a") \ match :- done.
```
（単に一回マッチして「match」が「done」になるだけのはず）
これの実行結果が、
```
done. str(a). @56.
```
になりました。`str`に接続されているアトム`a`がstring型ではなく普通のアトムになっています。
コンパイラが生成した中間コードを見てみると、
```
newatom      [6, 0, 'a'_1]
```
のような命令がありました．
`"a"` ではなく、`'a'`という普通のアトムを生成しています．

「\」を使わずに両辺に展開してやるときちんと動きます．

**Comment by sano97** [comment]
str("a").
 match.
 str("a") \ match :- done.
（単に一回マッチして「match」が「done」になるだけのはずだと思いました）
これの実行結果が、
 go. done. str(a). @56.
になったのですが、
（「str」の要素がstring型ではなく普通のアトムになっている？ガードにstring制約を書いたルールを追加したのですが、そのルールは発火しませんでした）

**Comment by sapphimoor** [comment]
田口です。
デバッグして、手元で正しく動作することが確認できました。

---
https://github.com/lmntal/lmntal-compiler/blob/51372937c494b37d8a213a30fda5c6ce47ba1511/src/compile/parser/SrcRule.java#L260
を
```java
ret.add(new SrcAtom(sa.getSrcName(), copySrcs(sa.getProcess())));
```
に変更し、また
https://github.com/lmntal/lmntal-compiler/blob/51372937c494b37d8a213a30fda5c6ce47ba1511/src/compile/parser/SrcAtom.java#L43-L51
このコンストラクタを参考に、新しいコンストラクタ
```java
	/**
	 * 指定された名前トークンと子供プロセスで初期化します
	 * @param srcname 名前トークン
	 * @param process 子供プロセス
	 */
	public SrcAtom(SrcName srcname, LinkedList process)
	{
		this(srcname, process, -1,-1);
	}
```
をオーバーロードしました。

Body にアトムを複製する際に String として SrcAtom の第 1 引数にアトム名を投げると、PLAIN トークンとして処理されて（文字列のアトムとしての情報が失われて）しまうことが原因でした。

**Comment by sapphimoor** [comment]
プルリクです。
https://github.com/lmntal/lmntal-compiler/pull/102#issue-678344380
